services:
  srs-app:
    build: .
    ports:
      - "5173:5173"  # Conecta tu puerto 5173 con el de Docker
    volumes:
      - .:/app       # ¡ESTO ES ORO! Sincroniza tu código en tiempo real
      - /app/node_modules # Protege los módulos internos de Docker
    environment:
      - WATCHPACK_POLLING=true # Obliga a Vite a detectar cambios en Docker
