services:
  srs-medic:
    build:
      context: .
      dockerfile: Dockerfile.runtime
    image: srs-medic:local
    container_name: srs-medic
    restart: unless-stopped
    ports:
      - "8080:80"
