/** Frases de bienvenida — tono humano, cercano al equipo clínico (MX).
 *  Se rotan por día + un hash del userId para que cada usuario vea una distinta. */

export const MOTIVATIONAL_PHRASES = {
  default: [
    "Hoy alguien va a sentirse mejor gracias a lo que haces.",
    "Cuidar es un privilegio. Gracias por estar aquí.",
    "Con calma, con detalle y con el corazón: así se atiende bien.",
    "Cada día en este centro médico es una oportunidad de hacer la diferencia.",
    "Tu presencia aquí importa más de lo que imaginas.",
    "Lo que haces con dedicación deja huella en quienes confían en nosotros.",
    "La excelencia no es un acto, es un hábito. Y tú lo demuestras.",
    "Hoy también es un buen día para dar lo mejor de ti.",
    "El trabajo en equipo es el secreto de una atención de calidad.",
    "Gracias por poner el corazón en cada tarea, por pequeña que parezca.",
  ],
  admin: [
    "Cuando el equipo tiene orden, el paciente lo nota en cada consulta.",
    "Tu trabajo hace que todo lo demás pueda fluir sin fricción.",
    "Hoy también cuidas a quienes cuidan.",
    "Detrás de cada consulta exitosa hay una administración que funciona.",
    "La claridad en los procesos es la base de una clínica que inspira confianza.",
    "Un sistema bien gestionado permite que los médicos se concentren en lo que mejor saben hacer.",
    "Cada decisión que tomas impacta positivamente en la experiencia del paciente.",
    "Hoy lideras con el ejemplo de una operación impecable.",
    "La eficiencia administrativa también es medicina: evita estrés, ahorra tiempo, salva vidas.",
    "El orden que construyes hoy será la tranquilidad del equipo mañana.",
    "Gestionar bien es también una forma de cuidar la salud.",
    "Tu capacidad de organizar hace que este centro respire armonía.",
  ],
  admin_maestro: [
    "Tu mirada sostiene a todo el centro. Gracias por ese cuidado invisible.",
    "Cuando lideras con claridad, el equipo respira y el paciente gana.",
    "Un timón firme lleva al barco a buen puerto. Hoy tú eres ese timón.",
    "La visión que aportas transforma una clínica en un verdadero centro de salud.",
    "Liderar no es mandar, es inspirar. Y tú lo haces cada día.",
    "Tu experiencia guía, tu confianza impulsa, tu presencia da seguridad.",
    "Cada área del centro funciona mejor porque sabes escuchar y decidir.",
    "El legado de un buen líder se mide en la calidad de su equipo. Y el tuyo es extraordinario.",
    "Hoy el centro médico es mejor que ayer gracias a tu dirección.",
    "La excelencia se construye desde arriba, y tú pones los cimientos.",
  ],
  medico: [
    "Escuchar con atención ya es mitad del diagnóstico.",
    "Hoy alguien confía en ti con lo más valioso: su salud.",
    "Que cada consulta tenga tiempo, respeto y buenas decisiones.",
    "Tus manos curan, pero tu empatía sana el alma del paciente.",
    "Detrás de cada receta hay un médico que se tomó el tiempo de escuchar.",
    "La medicina es ciencia, pero también es el arte de entender al ser humano.",
    "Cada paciente que sale tranquilo de tu consultorio es un triunfo silencioso.",
    "Hoy tienes el privilegio de devolver la esperanza a quien la ha perdido.",
    "No tratas enfermedades, tratas personas. Esa es la diferencia.",
    "Tu conocimiento es valioso, pero tu trato humano lo es aún más.",
    "La confianza que depositan en ti es el mejor reconocimiento a tu labor.",
    "Un buen diagnóstico empieza cuando el paciente siente que puede contarlo todo.",
  ],
  doctor: [
    "Escuchar con atención ya es mitad del diagnóstico.",
    "Hoy alguien confía en ti con lo más valioso: su salud.",
    "Que cada consulta tenga tiempo, respeto y buenas decisiones.",
    "Tus manos curan, pero tu empatía sana el alma del paciente.",
    "Detrás de cada receta hay un médico que se tomó el tiempo de escuchar.",
    "La medicina es ciencia, pero también es el arte de entender al ser humano.",
    "Cada paciente que sale tranquilo de tu consultorio es un triunfo silencioso.",
    "Hoy tienes el privilegio de devolver la esperanza a quien la ha perdido.",
    "No tratas enfermedades, tratas personas. Esa es la diferencia.",
    "Tu conocimiento es valioso, pero tu trato humano lo es aún más.",
    "La confianza que depositan en ti es el mejor reconocimiento a tu labor.",
    "Un buen diagnóstico empieza cuando el paciente siente que puede contarlo todo.",
  ],
  enfermeria: [
    "Tu mirada en el pasillo a veces llega antes que cualquier estudio.",
    "La mano que cuida y el detalle que registras cambian el día de alguien.",
    "Hoy, como siempre: presencia, calidez y ojo clínico.",
    "Enfermería es el corazón del centro médico. Tú lo mantienes latiendo.",
    "Cada signo vital que tomas, cada nota que escribes, es un acto de cuidado profundo.",
    "El paciente quizá no recuerde tu nombre, pero nunca olvidará cómo lo hiciste sentir seguro.",
    "La vocación se nota en los pequeños gestos: arropar, escuchar, tranquilizar.",
    "Detrás de cada alta médica hay horas de enfermería que pocos ven pero todos necesitan.",
    "Tu presencia constante es el ancla emocional del paciente durante su estancia.",
    "Hoy serás quien marque la diferencia para alguien que necesita exactamente eso.",
  ],
  enfermera: [
    "Tu mirada en el pasillo a veces llega antes que cualquier estudio.",
    "La mano que cuida y el detalle que registras cambian el día de alguien.",
    "Hoy, como siempre: presencia, calidez y ojo clínico.",
    "Enfermería es el corazón del centro médico. Tú lo mantienes latiendo.",
    "Cada signo vital que tomas, cada nota que escribes, es un acto de cuidado profundo.",
    "El paciente quizá no recuerde tu nombre, pero nunca olvidará cómo lo hiciste sentir seguro.",
    "La vocación se nota en los pequeños gestos: arropar, escuchar, tranquilizar.",
    "Detrás de cada alta médica hay horas de enfermería que pocos ven pero todos necesitan.",
    "Tu presencia constante es el ancla emocional del paciente durante su estancia.",
    "Hoy serás quien marque la diferencia para alguien que necesita exactamente eso.",
  ],
  enfermero: [
    "Tu mirada en el pasillo a veces llega antes que cualquier estudio.",
    "La mano que cuida y el detalle que registras cambian el día de alguien.",
    "Hoy, como siempre: presencia, calidez y ojo clínico.",
    "Enfermería es el corazón del centro médico. Tú lo mantienes latiendo.",
    "Cada signo vital que tomas, cada nota que escribes, es un acto de cuidado profundo.",
    "El paciente quizá no recuerde tu nombre, pero nunca olvidará cómo lo hiciste sentir seguro.",
    "La vocación se nota en los pequeños gestos: arropar, escuchar, tranquilizar.",
    "Detrás de cada alta médica hay horas de enfermería que pocos ven pero todos necesitan.",
    "Tu presencia constante es el ancla emocional del paciente durante su estancia.",
    "Hoy serás quien marque la diferencia para alguien que necesita exactamente eso.",
  ],
  jefa_enfermeria: [
    "Cuidar al equipo también es cuidar al paciente.",
    "Tu liderazgo se nota en la calma del turno y en la calidad del cuidado.",
    "Hoy el área camina más segura porque tú estás al frente.",
    "Una jefa de enfermería que inspira es la mejor medicina para su equipo.",
    "Tu supervisión asegura que ningún detalle se escape y que cada paciente esté protegido.",
    "Guiar con firmeza y cuidar con ternura: esa es la marca de tu liderazgo.",
    "El estándar de calidad que exiges es el reflejo de tu compromiso con la vida.",
    "Cada protocolo que haces cumplir es una barrera más contra el error.",
    "Tu experiencia es el faro que guía a las nuevas generaciones de enfermería.",
    "Organizar, supervisar y motivar: hoy lo harás con la excelencia de siempre.",
  ],
  jefa: [
    "Cuidar al equipo también es cuidar al paciente.",
    "Tu liderazgo se nota en la calma del turno y en la calidad del cuidado.",
    "Hoy el área camina más segura porque tú estás al frente.",
    "Una jefa que inspira es la mejor medicina para su equipo.",
    "Tu supervisión asegura que ningún detalle se escape y que cada paciente esté protegido.",
    "Guiar con firmeza y cuidar con ternura: esa es la marca de tu liderazgo.",
    "El estándar de calidad que exiges es el reflejo de tu compromiso con la vida.",
  ],
  rh: [
    "Detrás de cada guardia hay personas. Gracias por cuidarlas.",
    "Un equipo respaldado atiende mejor. Tu labor se siente en piso.",
    "Cuidar del talento humano es tan importante como cuidar de la salud.",
    "Cada contrato, cada nómina, cada gestión tuya sostiene a quienes salvan vidas.",
    "Tu trabajo en RH asegura que el personal llegue motivado y se quede comprometido.",
    "La rotación baja y la satisfacción alta son tu mejor indicador de éxito.",
    "Hoy el equipo se siente respaldado porque saben que estás del otro lado.",
    "Gestionar personas en salud es un acto de vocación doble.",
  ],
  recepcion: [
    "La primera sonrisa del día del paciente suele ser la tuya.",
    "Orden, calidez y claridad: así empieza una buena atención.",
    "Hoy eres la puerta de entrada a la confianza.",
    "Tu amabilidad en la recepción puede calmar la ansiedad de quien llega preocupado.",
    "Cada cita que agendas con eficiencia es un paciente que se siente valorado.",
    "La paciencia y la sonrisa son tus mejores herramientas de trabajo.",
    "El paciente llega nervioso; tu calidez hace que se sienta en buenas manos.",
    "Organizar el flujo de pacientes también es una forma de cuidar su salud.",
  ],
  intendencia: [
    "Un espacio limpio también es un acto de cuidado.",
    "Tu trabajo hace que todos puedan concentrarse en el paciente.",
    "La higiene que mantienes es la primera barrera contra las infecciones.",
    "Cada superficie que desinfectas es un escudo invisible para pacientes y personal.",
    "Sin tu labor silenciosa, este centro no podría operar con seguridad.",
    "La excelencia en la limpieza es una forma de respeto hacia quienes atendemos.",
    "Hoy tu dedicación a los detalles hace que este lugar sea seguro para todos.",
    "El orden y la pulcritud que mantienes hablan de tu profesionalismo.",
  ],
  limpieza: [
    "Un espacio limpio también es un acto de cuidado.",
    "Tu trabajo hace que todos puedan concentrarse en el paciente.",
    "La higiene que mantienes es la primera barrera contra las infecciones.",
    "Cada superficie que desinfectas es un escudo invisible para pacientes y personal.",
    "Sin tu labor silenciosa, este centro no podría operar con seguridad.",
    "La excelencia en la limpieza es una forma de respeto hacia quienes atendemos.",
    "Hoy tu dedicación a los detalles hace que este lugar sea seguro para todos.",
    "El orden y la pulcritud que mantienes hablan de tu profesionalismo.",
  ],
  operativo: [
    "Lo que haces en segundo plano sostiene lo que pasa en consulta.",
    "Gracias por hacer que el día corra con menos tropiezos.",
    "Cada proceso que optimizas reduce el tiempo de espera y mejora la atención.",
    "La logística bien hecha es invisible, pero su ausencia se nota de inmediato.",
    "Tu capacidad de resolver problemas mantiene la operación fluyendo sin pausa.",
    "Hoy tu trabajo operativo permitirá que doctores y enfermeras se concentren en lo suyo.",
    "La eficiencia que aportas se traduce en pacientes mejor atendidos.",
    "Eres el engranaje silencioso que mantiene en marcha todo el centro.",
  ],
};

export const pickMotivationalPhrase = (roleKey, userId = "") => {
  const pool = MOTIVATIONAL_PHRASES[roleKey] || MOTIVATIONAL_PHRASES.default;
  const now = new Date();
  const dayOfYear = Math.floor((now - new Date(now.getFullYear(), 0, 0)) / 86400000);
  let hash = 0;
  for (let i = 0; i < (userId || "").length; i++) {
    hash = ((hash << 5) - hash) + userId.charCodeAt(i);
    hash |= 0;
  }
  const index = (dayOfYear + Math.abs(hash)) % pool.length;
  return pool[index];
};
